In [ ]:
import numpy as np
v = [1,2,0,4]
v2 = np.array(v)
print(type(v2))
print(v2 *2)

y = [3,4,7,1]
y2 = np.array(y)
sum = v2+y2


<class 'numpy.ndarray'>
[2 4 0 8]
[4 6 7 5]


In [ ]:
m= np.random.randint(10(5,4))
np.matmul(m, v2)



array([37, 25, 54, 44, 39])